# -*- coding: utf-8 -*-
"""capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf_dynwztbCn5regwiOTTov_h2ZO2ZHJ
"""

!pip install -q streamlit pyngrok google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# 
# import streamlit as st
# import google.generativeai as genai
# 
# 
# # Configure Gemini API
# genai.configure(api_key="AQ.Ab8RN6JXieVukoQtw-0owZs3FN2FimPCoz-2t4ZGFDUrr2FH-A")
# 
# 
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# 
# st.set_page_config(page_title="AI Learning Buddy Sonu", page_icon="🎓")
# 
# 
# st.title("🎓 AI Learning Buddy Sonu")
# 
# 
# topic = st.text_input("Enter a Topic")
# 
# 
# option = st.selectbox(
#     "Choose Activity",
#     [
#         "Explain Concept",
#         "Real-Life Example",
#         "Generate Quiz",
#         "Ask Anything"
#     ]
# )
# 
# 
# if st.button("Generate"):
# 
# 
#     if topic == "":
#         st.warning("Please enter a topic.")
#     else:
# 
# 
#         if option == "Explain Concept":
#             prompt = f"Explain {topic} in simple language for a beginner."
# 
# 
#         elif option == "Real-Life Example":
#             prompt = f"Give one simple real-life example of {topic}."
# 
# 
#         elif option == "Generate Quiz":
#             prompt = f"Create 5 MCQs on {topic} with answers."
# 
# 
#         else:
#             prompt = topic
# 
# 
#         response = model.generate_content(prompt)
# 
# 
#         st.write(response.text)

!nohup streamlit run app.py --server.port 8501 &

import time
time.sleep(10)

!cat nohup.out

!pip install -q pyngrok

from pyngrok import ngrok


ngrok.set_auth_token("3FrEFkmf2IZDKlUXihTUpByfnO6_29M6dF98sECDhgQmqDtYS")

public_url = ngrok.connect(8501)


print(public_url)

